### ISSUE TITLE
Statistics basic

### ISSUE THREAD

**Issue by piskula** [piskula/FuelUp#1]
## Important
- [x] average fuel consumption
- [x] average kilometres/miles per litre
- [x] total tracked distance
- [x] period of registred expenses/fillups (i.e. tracking for 1year and 3months)

## Total
- [x] total number of fill ups
- [x] total number of expenses
- [x] total fuel volume
- [x] total price (fuel + fillups)
- [x] total fuel price
- [x] total expense price

## Average per distance
- [x] average total  price per ~~kilometer~~ 100kilometers
- [x] average fuel price per ~~kilometer~~ 100kilometers
- [x] average expense price per ~~kilometer~~ 100kilometers

## Average per time
- [x] average total costs per week
- [x] average total costs per month
- [x] average total costs per year
- [x] average fuel costs per week
- [x] average fuel costs per month
- [x] average fuel costs per year
- [x] average expense costs per week
- [x] average expense costs per month
- [x] average expense costs per year

- [x] average distance per day
- [x] average distance per week
- [x] average distance per month
- [x] average distance per year

# Average fuel
- [x] average fuel cost per litre
- [x] average fuel volume per fillup
- [x] average fuel cost per fillup

# Extreme values
- [x] Best fuel consumption
- [x] Worst fuel consumption
- [x] Cheapest fuel price per litre
- [x] Most expensive fuel price per litre
- [x] Largest distance between two fill ups
- [x] Smallest distance between two fill ups

**Comment by MartinStyk** [comment]
@piskula , check it out. Is it ok? Do we want more?
