### ISSUE TITLE
Wrong fill up price computation with UK currency

### ISSUE THREAD

**Issue by MartinStyk** [piskula/FuelUp#46]
1 Open car with UK currency
2 open fill ups
3 I see - volume 7.32 GAL, unit price p 118.1/l, total price 39.32 libra. 

I expect it should be 7.32 *  1.181 != 39.32

**Comment by piskula** [comment]
No.
It should be 7.32 * 1.181 * GallonToLitres == 39.32
Price is PER LITRE but Fuel Volume is in GALLONS. I think it is correct from what I saw in Google Street View gas stations and on the internet. Maybe I am wrong.
