### ISSUE TITLE
Handle small number of entries in charts

### ISSUE THREAD

**Issue by MartinStyk** [piskula/FuelUp#56]
When there is a 1 or two full fillups, charts show nothing at all

**Comment by piskula** [comment]
I think in that case the graph is correct, but maybe we can slightly add some opacity to that graph and place there some message, e.g. This graph is not relevent because of data insufficiency.

**Comment by piskula** [comment]
Maybe som Toast or Snackbar can be solution instead of opacity.

**Comment by MartinStyk** [comment]
@piskula , it is not an issue. The real problem is there is nothing visible when there is only one fill up. You see nothing, only chart axes
